<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Brand;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $brands = [
            [   
                "category_id" => 4,
                "name" => "Safaricom",
                "about" => "Safaricom PLC is a listed Kenyan mobile network operator headquartered at Safaricom House in Nairobi, Kenya. It is the largest telecommunications provider in Kenya, and one of the most profitable companies in the East and Central Africa region.",
                "rating" => 0.0,
                "website_url" => "http://www.safaricom.co.ke/",
                "company_phone" => "+254 722 002 100",
                "company_email" => "customercare@safaricom.co.ke",
                "address" => "SAFARICOM HOUSE. Waiyaki Way, Westlands. Nairobi, Kenya.",
                "logo_path" => "/images/logos/1.png",
                "is_verified" => 1,
                "is_claimed" => 1,
            ],
            [   
                "category_id" => 1,
                "name" => "KCB Bank",
                "about" => "KCB Bank Kenya Limited is a financial services provider headquartered in Nairobi, Kenya. It is licensed as a commercial bank, by the Central Bank of Kenya, the national banking regulator. The bank has also been running Agency banking model.",
                "rating" => 0.0,
                "website_url" => "http://ke.kcbgroup.com/",
                "company_phone" => "+254 711 087 000",
                "company_email" => "contactcentre@kcb.co.ke",
                "address" => "Kencom House, 8th Floor, Moi Avenue. Nairobi, Kenya",
                "logo_path" => "/images/logos/2.png",
                "is_verified" => 1,
                "is_claimed" => 1,
            ],
            [   
                "category_id" => 2,
                "name" => "Jubilee Insurance",
                "about" => "The Jubilee Insurance Company of Kenya, mostly known as Jubilee Insurance, is an insurance company in Kenya, which has the largest economy in the East African Community.",
                "rating" => 0.0,
                "website_url" => "https://jubileeinsurance.com/ke/",
                "company_phone" => "+254 20 328 1000",
                "company_email" => "info@jubileekenya.com",
                "address" => "Jubilee Insurance House, Wabera Street. Nairobi, Kenya",
                "logo_path" => "/images/logos/3.png",
                "is_verified" => 1,
                "is_claimed" => 1,
            ],
            [   
                "category_id" => 4,
                "name" => "Telkom",
                "about" => "Telkom Kenya is an integrated telecommunications provider in Kenya. It was previously a part of the Kenya Posts and Telecommunications Corporation which was the sole provider of both postal and telecommunication services.",
                "rating" => 0.0,
                "website_url" => "https://telkom.co.ke/",
                "company_phone" => "+254 20 222 1000",
                "company_email" => "customercare@telkom.co.ke",
                "address" => "Telkom Plaza, Ralph Bunche Rd. Nairobi, Kenya.",
                "logo_path" => "/images/logos/4.png",
                "is_verified" => 1,
                "is_claimed" => 1,
            ],
            [   
                "category_id" => 5,
                "name" => "Jumia",
                "about" => "Jumia is a Pan-African technology company that is built around a marketplace, logistics service and payment service. The logistics service enables the delivery of packages through a network of local partners while the payment services facilitate the payments of online transactions within Jumia's ecosystem.",
                "rating" => 0.0,
                "website_url" => "https://www.jumia.co.ke/",
                "company_phone" => "+254 711 011 011",
                "company_email" => "customercare@jumia.co.ke",
                "address" => "Kaka House, Mua Close, Westlands. Nairobi, Kenya.",
                "logo_path" => "/images/logos/5.png",
                "is_verified" => 1,
                "is_claimed" => 1,
            ],
            [   
                "category_id" => 5,
                "name" => "Hotpoint",
                "about" => "Hotpoint is a British brand of domestic appliances. Ownership of the brand is split between American company Whirlpool, which has the rights in Europe, and Chinese company Haier, which has the rights in the Americas through its purchase of GE Appliances in 2016.",
                "rating" => 0.0,
                "website_url" => "https://hotpoint.co.ke/",
                "company_phone" => "+254 800 720 404",
                "company_email" => "customercare@jumia.co.ke",
                "address" => "Misha Towers, Westlands Rd. Nairobi, Kenya.",
                "logo_path" => "/images/logos/6.png",
                "is_verified" => 1,
                "is_claimed" => 1,
            ],
            [   
                "category_id" => 5,
                "name" => "University of Nairobi",
                "about" => "The University of Nairobi is a collegiate research university based in Nairobi. It is the largest university in Kenya. Although its history as an educational institution dates back to 1956, it did not become an independent university until 1970.",
                "rating" => 0.0,
                "website_url" => "https://www.uonbi.ac.ke/",
                "company_phone" => "+254 20 224 5566",
                "company_email" => "admissions@uonbi.ac.ke",
                "address" => "University of Nairobi, University Way, Nairobi Kenya.",
                "logo_path" => "/images/logos/7.png",
                "is_verified" => 1,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 3,
                "name" => "Aga Khan Hospital",
                "about" => "The Aga Khan University Hospital in Nairobi, established in 1958 is a 254-bed long-term care facility offering general medical services, specialist clinics and diagnostic services. The hospital receives referrals for specialised medical care and diagnostic services from various hospitals and clinics in the region. ",
                "rating" => 0.0,
                "website_url" => "https://www.agakhanhospitals.org/en/kenya",
                "company_phone" => "+254 20 366 2000",
                "company_email" => "akuh.information@aku.edu",
                "address" => "Aga Khan University Hospital, 3rd Parklands Avenue, Limuru Road, Nairobi, Kenya.",
                "logo_path" => "/images/logos/8.png",
                "is_verified" => 1,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 3,
                "name" => "Kenyatta National Hospital",
                "about" => "Kenyatta National Hospital located in Nairobi, is the oldest hospital in Kenya. Established in 1901 with a capacity of about 40 beds as Native Civil Hospital, it was renamed King George VI in 1952.",
                "rating" => 0.0,
                "website_url" => "https://knh.or.ke/",
                "company_phone" => "020 272 6300",
                "company_email" => "knhadmin@knh.or.ke",
                "address" => "Hospital Road off Ngong Road,Nairobi, Kenya.",
                "logo_path" => "/images/logos/9.png",
                "is_verified" => 1,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 12,
                "name" => "Furniture Palace",
                "about" => "Furniture Palace was set up in 2002 to provide excellent quality contemporary furniture and in 2009 via the internet, with the focus on great design, fantastic quality, and value for money.",
                "rating" => 0.0,
                "website_url" => "https://furniturepalacekenya.com/",
                "company_phone" => "+254 791 777 000",
                "company_email" => "info@furniturepalace.co.ke",
                "address" => "Mombasa Road Opposite Parkside Towers, Nairobi, Kenya.",
                "logo_path" => "/images/logos/11.png",
                "is_verified" => 1,
                "is_claimed" => 1,
            ],
            [   
                "category_id" => 12,
                "name" => "Victoria Furniture",
                "about" => "Victoria Furnitures Ltd is the leading supplier of high quality office furniture in East Africa. We are a pioneer in the industry offering the market greater choice, innovative and ergonomic designs as well as environmentally friendly furniture.",
                "rating" => 0.0,
                "website_url" => "https://www.victoriafurnitures.com/",
                "company_phone" => "+254 770 876 140",
                "company_email" => "sales@victoriaoffice.co.ke",
                "address" => "9, Parklands Road, Westlands, Nairobi, Kenya.",
                "logo_path" => "/images/logos/12.png",
                "is_verified" => 1,
                "is_claimed" => 1,
            ],
            [   
                "category_id" => 10,
                "name" => "Sarova Hotels",
                "about" => "The success of Sarova Hotels and Resorts has been built on a commitment to refreshing African hospitality. A beautiful history of family and friendship spanning over 45 years comes alive in our superior service delivery.",
                "rating" => 0.0,
                "website_url" => "https://www.sarovahotels.com/",
                "company_phone" => "+254 709 111 000",
                "company_email" => "centralreservations@sarovahotels.com",
                "address" => "Kenyatta Avenue, Nairobi, Kenya.",
                "logo_path" => "/images/logos/13.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 10,
                "name" => "Pride Inn Hotels",
                "about" => "PrideInn chain of hotels consists of 8 hotels PrideInn Paradise Beach Resort and Spa, PrideInn Flamingo Beach Resort, PrideInn Mombasa City, PrideInn Nyali, PrideInn Diani, PrideInn Westlands, and PrideInn Azure which range from luxury to economy. We combine excellent service with a personal touch to ensure that all our guests receive world-class service in all our hotels in Kenya.",
                "rating" => 0.0,
                "website_url" => "https://www.prideinn.co.ke/",
                "company_phone" => "+254 709 532 000",
                "company_email" => "website@prideinn.co.ke",
                "address" => "Muthithi Road, Westlands, Nairobi, Kenya.",
                "logo_path" => "/images/logos/14.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 11,
                "name" => "Kenya Airways",
                "about" => "Kenya Airways is the national airline of Kenya with headquarters in Nairobi. This company started operating in 1977 after the breakup of the East African Community which led to the breakup of East African Airways. Currently this company offers services in Africa, Europe and India.",
                "rating" => 0.0,
                "website_url" => "https://www.kenya-airways.com/ke/",
                "company_phone" => "+254 711 024 308",
                "company_email" => "customer.relations@kenya-airways.com",
                "address" => "ABSA Towers, Nairobi, Kenya.",
                "logo_path" => "/images/logos/15.png",
                "is_verified" => 1,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 11,
                "name" => "Jambo Jet",
                "about" => "Jambojet, a brand of Kenya Airways, is Kenya's first low-cost airline. Operating from Jomo Kenyatta International Airport in Nairobi, Jambojet has set to revolutionize the way you travel by opening up the skies for all to fly for less. We aim to provide affordable air travel because flying really is for everyone.",
                "rating" => 0.0,
                "website_url" => "https://www.jambojet.com/",
                "company_phone" => "+254 711 024 545",
                "company_email" => "info@jambojet.com",
                "address" => "Barclays Plaza, Market St, Starehe, Nairobi, Kenya.",
                "logo_path" => "/images/logos/16.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 11,
                "name" => "Kenya Railways",
                "about" => "The history of rail transport in Kenya dates back to the period between 1891 and 1895 when raging debates ensued in the British parliament over the necessity of constructing a railway line through a country owned by the Maasai and unlettered African tribesmen.",
                "rating" => 0.0,
                "website_url" => "https://krc.co.ke/",
                "company_phone" => "+254 709 388 887",
                "company_email" => "info@krc.co.ke",
                "address" => "Haile Selassie Road, Nairobi, Kenya.",
                "logo_path" => "/images/logos/18.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 3,
                "name" => "The Nairobi Hospital",
                "about" => "The Nairobi Hospital is a non-profit organization that is leading in medical expertise and service provision, with deservedly earned recognition throughout East Africa and beyond as an advanced diagnostic, treatment and referral centre.",
                "rating" => 0.0,
                "website_url" => "https://thenairobihosp.org/",
                "company_phone" => "+254 703 082 000",
                "company_email" => "https://thenairobihosp.org/",
                "address" => "The Nairobi Hospital, Argwings Kodhek Rd, Nairobi, Kenya.",
                "logo_path" => "/images/logos/19.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 7,
                "name" => "Catholic University of Eastern Africa",
                "about" => "The Catholic University of Eastern Africa (CUEA), like most other universities, started in a modest way. It commenced as a graduate school of theology known as the Catholic Higher Institute of Eastern Africa (CHIEA).",
                "rating" => 0.0,
                "website_url" => "https://www.cuea.edu/",
                "company_phone" => "+254 709 691 000",
                "company_email" => "admissions@cuea.edu",
                "address" => "Bogani East Road, off Magadi Road, Next to Galleria Mall, Nairobi, Kenya.",
                "logo_path" => "/images/logos/20.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 7,
                "name" => "United States International University Africa",
                "about" => "In 1927 Leland Ghent Stanford chartered a private graduate institution called Balboa Law College in San Diego (USA), which later changed its name toBalboa University in 1945. In 1952, Balboa University again changed its name to California Western University, and a year later Dr. William C. Rust became the university's president.",
                "rating" => 0.0,
                "website_url" => "https://www.usiu.ac.ke/",
                "company_phone" => "+254 730 116 000",
                "company_email" => "admit@usiu.ac.ke",
                "address" => "USIU Road, Off Thika Road (Exit 7), Nairobi, Kenya.",
                "logo_path" => "/images/logos/21.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 11,
                "name" => "Bolt",
                "about" => "Bolt is an Estonian mobility company that offers vehicle for hire, micromobility, car-sharing, and food delivery services headquartered in Tallinn and operating in over 500 cities in more than 45 countries in Europe, Africa, Western Asia and Latin America.",
                "rating" => 0.0,
                "website_url" => "https://bolt.eu/",
                "company_phone" => "Not available",
                "company_email" => "nairobi@bolt.eu",
                "address" => "Online.",
                "logo_path" => "/images/logos/25.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 11,
                "name" => "Uber",
                "about" => "Uber Technologies, Inc., based in San Francisco, provides mobility as a service, ride-hailing, food delivery, package delivery, couriers, and freight transportation.",
                "rating" => 0.0,
                "website_url" => "https://www.uber.com/ke/en/",
                "company_phone" => "Not available",
                "company_email" => "infonbicbd@jkuat.ac.ke",
                "address" => "Prof David Wasawo Drive, Riverfront Building, Nairobi, Kenya.",
                "logo_path" => "/images/logos/26.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 6,
                "name" => "Optiven",
                "about" => "Optiven is a leading brand in the region and has a number of flourishing Strategic Business Units (SBUs) that include Optiven Real Estate, Optiven Construction, Optiven Insurance,  Optiven Homes, and Optiven Water. The firm has also gained a foothold into the hospitality industry with its GMC Place in Kitengela and two food franchises that include Eagle Peak Spur and Panarottis.",
                "rating" => 0.0,
                "website_url" => "https://www.optiven.co.ke/",
                "company_phone" => "+254  790 300 300",
                "company_email" => "info@optiven.co.ke",
                "address" => "Absa Towers, Loita St., Nairobi, Kenya.",
                "logo_path" => "/images/logos/35.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 5,
                "name" => "My Dawa",
                "about" => "MYDAWA, is founded on the premise of Live Well, Stay Well and Get Well is here to ensure that every Kenyan can get quality, secure and affordable medicine and wellness products online.",
                "rating" => 0.0,
                "website_url" => "http://www.mydawa.com",
                "company_phone" => "+254 20 521 9999",
                "company_email" => "support@mydawa.com",
                "address" => "Westside Towers, Lower Kabete Road, Nairobi, Kenya.",
                "logo_path" => "/images/logos/40.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 9,
                "name" => "KTN",
                "about" => "KTN News is a 24-hour based television network created by the Kenya Television Network, which associates with current events and affairs facing Kenya. It is mostly news, updates and stories coverage and is one of the fastest growing TV stations in Kenya.",
                "rating" => 0.0,
                "website_url" => "https://www.standardmedia.co.ke/ktnhome/",
                "company_phone" => "+254 719 012 111",
                "company_email" => "corporate@standardmedia.co.ke",
                "address" => "Standard Group Plc HQ Office, Mombasa Road, Nairobi, Kenya.",
                "logo_path" => "/images/logos/30.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
            [   
                "category_id" => 9,
                "name" => "Citizen",
                "about" => "Citizen TV is a Kenyan free-to-air news television channel owned by Royal Media Services and broadcasting mostly in English and Swahili. It was started in 1999 and relaunched in June 2006.",
                "rating" => 0.0,
                "website_url" => "https://www.citizen.digital/",
                "company_phone" => "+254 719 060 000",
                "company_email" => "digitalsales@royalmedia.co.ke",
                "address" => "Maalim Juma Road Off Dennis Pritt Road, Nairobi, Kenya.",
                "logo_path" => "/images/logos/32.png",
                "is_verified" => 0,
                "is_claimed" => 0,
            ],
        ];

        foreach($brands as $brand) {
            Brand::create($brand);
        }
    }
}
